<!DOCTYPE html>
<html>
<body>

<h1 style="text-align: center;">&nbsp;<strong>European Butterfly Trait Database</strong></h1>
<h2>This site host a comprehensive database of non-biotope traits of European and North African (Maghreb) butterflies ( 216 traits * 507 taxa)</h2>
<p></p>
<h3><p>The database is an output from two sECURE workshops kindly supported by sDiv, the Synthesis Centre of the German Centre for Integrative Biodiversity Research (iDiv) Halle‐Jena‐Leipzig (DFG FZT 118; WG 4.28 sECURE). </p>
<p><strong>The authors of the European butterfly trait database are: </strong>Joseph Middleton Welling<sup>1</sup>, Leonardo Dapporto<sup>2</sup>, Enrique Garc&iacute;a-Barros<sup>3</sup>, Martin Wiemers<sup>4,5</sup>, Piotr Nowicki<sup>6</sup>, Elisa Plazio<sup>6</sup>, Simona Bonelli<sup>7</sup>, Michele Zaccagno<sup>7</sup>, Martina &Scaron;a&scaron;ić<sup>8</sup>, Jana Liparova<sup>9</sup>, Oliver Schweiger<sup>5</sup>, Alexander Harpke<sup>5</sup>, Martin Musche<sup>5</sup>, Josef Settele<sup>5,10</sup>, Reto Schmucki<sup>11</sup>,Tim Shreeve<sup>1</sup><strong>&nbsp;</strong></p>
<p><strong>Affiliations</strong></p>
<ol>
<li>Centre for Ecology, Environment and Conservation, Faculty of Health and Life Sciences, Oxford Brookes University, Oxford, OX3 0BP UK</li>
<li>Dipartimento di Biologia dell'Universit&agrave; di Firenze, Via Madonna del Piano, 6, 50019 Comune di Sesto Fiorentino, Firenze, Italy</li>
<li>Department of Biology, Universidad Aut&oacute;noma de Madrid, Campus Cantoblanco, 28049, Madrid, Spain</li>
<li>Senckenberg Deutsches Entomologisches Institut, Eberswalder Str. 90, 15374 M&uuml;ncheberg, Germany</li>
<li>Department of Community Ecology, Helmholtz Centre for Environmental</li>
</ol>
<p>Research - UFZ, Theodor-Lieser-Strasse 4, 06120 Halle, Germany</p>
<ol start="6">
<li>Institute of Environmental Sciences, Jagiellonian University, Gronostajowa 7, 30-387, Krak&oacute;w, Poland</li>
<li>Department of Life Sciences and Systems Biology, Universit&agrave; degli Studi di Torino, Via Accademia Albertina, 13 10125, Torino, Italy</li>
<li>Croatian Natural History Museum, Demetrova 1, 10 000, Zagreb, Croatia</li>
<li>Institute of Entomology, Biology Centre CAS, Branisovska 31, Ceske Budejovice, Czech Republic</li>
<li>iDiv, German Centre for Integrative Biodiversity Research, Halle-Jena-Leipzig, Deutscher Platz 5e, 04103 Leipzig, Germany</li>
</ol>
<p>11.UK Centre for Ecology and Hydrology, Maclean Building, Benson Lane, Crowmarsh Gifford, Wallingford, OX10 8BB UK</p><h3>

</body>
</html>

theme: jekyll-theme-slate